version: "2.1"
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    environment:
      - TZ=Asia/Tokyo
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./teamspeak_config:/var/ts3server/
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
